config/routes.rb
Rails.application.routes.draw do


 
  resources :organizations
  resources :seeks

  resources :donators
  resources :toys
  resources :donors_toys
  resources :don_and_seek_connects
  resources :org_and_toy_connects
  resources :comments_org_donor_toys
  resources :comments_don_and_seeks
  resources :received_toys
  resources :orgprofiles
  # You can have the root of your site routed with "root"
  root 'toys#index'
  get 'login' => 'sessions#new', as: :login
  post 'login_don' => 'sessions#create_don_session'
  post 'login_org' => 'sessions#create_org_session'
  patch 'update_toy' => 'toys#update', as: :update_toy
  delete 'logout' => 'sessions#destroy', as: :logout
  # get 'seeks' => 'seeks#index', as: :seeks_path 

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/comments_don_and_seek.rb
class CommentsDonAndSeek < ActiveRecord::Base

	belongs_to :organization
	belongs_to :donator
	belongs_to :don_and_seek_connect
	
end

app/models/comments_org_donor_toy.rb
class CommentsOrgDonorToy < ActiveRecord::Base
	belongs_to :organization
	belongs_to :donator
	belongs_to :org_and_toy_connect
end

app/models/don_and_seek_connect.rb
class DonAndSeekConnect < ActiveRecord::Base
	belongs_to :donator
	belongs_to :seek
	belongs_to :organization
	has_many :comments_don_and_seek
	has_many :received_toys
end

app/models/donator.rb
class Donator < ActiveRecord::Base
	has_secure_password

	# Paperclip below
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

	has_many :donors_toys
	has_many :toys, through: :donors_toys
	has_many :don_and_seek_connects
	has_many :seeks, through: :don_and_seeks_connects
	has_many :comments_org_donor_toys
	has_many :org_and_toy_connects
	has_many :comments_don_and_seeks
	has_many :received_toys

end

app/models/donors_toy.rb
class DonorsToy < ActiveRecord::Base
	
	belongs_to :donator
	belongs_to :toy
	has_many :organizations, through: :org_and_toy_connects
	has_many :org_and_toy_connects, dependent: :destroy
	has_many :received_toys

	# scope :multiple_donated_toys -> { |x,y| DonorsToy.where}
end

app/models/org_and_toy_connect.rb
class OrgAndToyConnect < ActiveRecord::Base
	belongs_to :organization
	belongs_to :donator
	belongs_to :donors_toy
	has_many :comments_org_donor_toys
	has_many :received_toys

end

app/models/org_profile.rb
class OrgProfile < ActiveRecord::Base
	belongs_to :organization
end

app/models/organization.rb
class Organization < ActiveRecord::Base
	has_secure_password

	# Paperclip below
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
	
	# Geocode Below
	geocoded_by :address
	after_validation :geocode

	# relationships
	has_many :seeks
	has_many :toys, through: :seeks
	has_many :org_and_toy_connects
	has_many :donors_toys, through: :org_and_toy_connects
	has_many :comments_org_donor_toys
	has_many :don_and_seek_connects
	has_many :comments_don_and_seeks
	has_many :received_toys
	has_one :org_profile
end

app/models/received_toy.rb
class ReceivedToy < ActiveRecord::Base
	belongs_to :organization
	belongs_to :donator
	belongs_to :donors_toy
	belongs_to :seek
	belongs_to :org_and_toy_connect
	belongs_to :don_and_seek_connect
end

app/models/seek.rb
class Seek < ActiveRecord::Base
	belongs_to :organization
	belongs_to :toy
	has_many :don_and_seek_connects, dependent: :destroy
	has_many :donators, through: :don_and_seek_connects
	has_many :received_toys
	
end

app/models/toy.rb
class Toy < ActiveRecord::Base
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  has_many :donors_toys
  has_many :donators, through: :donors_toys
  has_many :seeks
  has_many :organizations, through: :seeks

  # belongs_to :organization
end

app/controllers/donators_controller.rb
class DonatorsController < ApplicationController
  def new
    @don = Donator.new
  end

  def index
    @dons = Donator.all
  end

  def create
    @don = Donator.new(don_params)
    if @don.save
      redirect_to @don
      flash[:notice] = "Your account has been created."
    else
      redirect_to :back
      flash[:notice] = "There was a problem creating your account."
    end
  end

  def show
    @don = Donator.find(params[:id])
    @organdtoy = OrgAndToyConnect.new
  end

  def edit
  end

  def destroy
    @don = Donator.find(params[:id])
    @don.destroy
    redirect_to root_path
  end
  private
  def don_params
    params.require(:donator).permit(:username, :email, :password, :avatar)
  end
end

app/controllers/seeks_controller.rb
class SeeksController < ApplicationController
  def index
    @seeks = Seek.all
  end

  def new
    @seek = Seek.new
  end

  def create
    @seek = Seek.new(seek_params)
    @seek.organization_id = current_org.id 
    @seek.toy_id = params[:seek][:toy_id]
    if @seek.save
      flash[:notice] = "Your seek was created."
      redirect_to @current_org
    else
      flash[:notice] = "There was a problem creating your seek."
      redirect_to :back
    end
  end

  def show
    @seek = Seek.find(params[:id])
    @donandseek = DonAndSeekConnect.new
  end

  def update
    @seek = Seek.find(params[:id])
    if @seek.update(seek_params)
      flash[:notice] = "Your toy has been marked as sent."
      redirect_to :back
    else
      flash[:notice] = "something went wrong. please try again."
      redirect_to :back
    end
  end

  def destroy
    @seek = Seek.find(params[:id])
    @seek.destroy
    flash[:notice] = "Your seek has been destroyed."
    redirect_to :back
  end

  private

  def seek_params
    params.require(:seek).permit( :organization_id, :toy_id, :comment, :active, :sent)
  end

end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
	def index
		@toys = Toy.all
		@donorstoy = DonorsToy.new
		@seek = Seek.new
	end

	def new
		@toy = Toy.new
	end

	def edit
		@toy = Toy.find(params[:id])
		@orgs = Organization.all
	end

	def update
		@toy = Toy.find(params[:id])
		@orgs = Organization.all
		if @toy.update_attributes(toy_params)
			flash[:notice] = "Your Donation has been saved!"
			redirect_to @toy
		else
			flash[:notice] = "something went wrong"
			redirect_to :back
		end
	end

	def create
		@toy = Toy.new(toy_params)
		if @toy.save
			flash[:notice] = "Your Toy Was Created"
			redirect_to @toy
		else
			flash[:notice] = "there was a problem creating your toy."
			redirect_to :back
		end
	end

	def show
		@toy = Toy.find(params[:id])
		@donorstoy = DonorsToy.new
		@seek = Seek.new
	end

	def destroy
		@toy = Toy.find(params[:id])
		@toy.destroy
		flash[:notice] = "Your toy has been deleted."
		redirect_to root_path
	end

	private
	def toy_params
  		params.require(:toy).permit(:name, :image, :donator_id, :donated?, :organization_id, :description, :category, :age_range)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donators_helper.rb
module DonatorsHelper
end

app/helpers/donors_toys_helper.rb
module DonorsToysHelper
end

app/helpers/org_profiles_helper.rb
module OrgProfilesHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/received_toys_helper.rb
module ReceivedToysHelper
end

app/helpers/seeks_helper.rb
module SeeksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/views/donators/edit.html.erb
<h1>Donators#edit</h1>
<p>Find me in app/views/donators/edit.html.erb</p>

app/views/donators/index.html.erb
<h1>All Donators Page</h1>
<% @dons.each do |d| %>
<%= link_to d.username, d, method: :get, :class => "link_to_buttons" %>
<% end %>

app/views/donators/new.html.erb
<h1>Create a New Donator Account</h1>
<%= form_for @don do |f| %>
<%= f.label :Username %>
<%= f.text_field :username %>
<%= f.label :Email %>
<%= f.email_field :email %>
<%= f.label :Avatar %>
<%= f.file_field :avatar %>
<%= f.label :Password %>
<%= f.password_field :password %>
<%= f.label :Password_Confirmation %>
<%= f.password_field :password_confirmation %>
<%= f.submit :Create %>
<% end %>

app/views/donators/show.html.erb
<h1 class="profile_headline"><%= @don.username %>'s Page</h1>
<div class="profile_contact">
  <%= image_tag @don.avatar.url(:medium), :class => "org_pic" %>
  <h4 class="org_info">Email: <%= @don.email %></h4>
  <h4 class="org_info"># of donations: <%= @don.received_toys.count %></h4>
</div>
  <!-- Toy Listing Section -->
<h4 id="seekers_show" class = "display_buttons">Show Available Toys</h4>
<h4 id="seekers_hide" class="display_buttons">Hide Available Toys</h4>
<div id="profile_orgseek">
  <% if @don.donors_toys.count == 0  %>
    <h4><%= link_to "Start Adding available toys to your closet", toys_path, :class => "display_buttons" %></h4>
  <% else %>
    <h3>These are the toys I have available for donation!</h3>
      <% @don.donors_toys.each do |t| %>
        <% if t.sent == false %>
        <!-- section to check if toy id is the same. -->
        <div class="seek_item_box">
          <%= link_to t.toy.name, t, method: :get, :class => "link_to_toy_show" %>
          <%= link_to(image_tag(t.toy.image.url(:thumb)), t, method: :get, :class => "link_to_img") %>
          <% if logged_in_org? %>  
            <%= form_for(@organdtoy) do |f| %>
              <%= f.hidden_field(:organization_id, :value => current_org.id) %>
              <%= f.hidden_field(:donors_toy_id, :value => t.id)%>
              <%= f.hidden_field(:donator_id, :value => @don.id)%>
              <%= f.hidden_field(:active, :value => true) %>
              <%= f.submit "Request_toy", :class => "RSVP_button" %>
            <% end %>
          <% end %>
        </div>  
        <% end %>  
      <% end %>
    <% end %>
  </div>
  <h4 id="received_show" class="display_buttons">Display Complete Donations</h4>
  <h4 id="received_hide" class="display_buttons">Hide Complete Donations</h4> 
  <div id = "profile_received"> 
    <% if @don.received_toys.count == 0 %>
      <h4>I have not made any donations</h4>
    <% else %>
    <h4>These are the toys I have donated</h4>  
    <% @don.received_toys.each do |t| %>
      <div class = "received_toy_box">
        <% if t.donors_toy_id != nil %>
          <%= t.donors_toy.toy.name %>
          <%= image_tag t.donors_toy.toy.image.url(:thumb) %>
        <% end %>
        <% if t.seek_id != nil %>
          <%= t.seek.toy.name %>
          <%= image_tag t.seek.toy.image.url(:thumb) %>
        <% end %>
      </div>  
    <% end %>
  <% end %>
</div>
<!-- Making sure it is correct donator before displaying message section -->
<% if logged_in_don? && current_don.id == @don.id %>  
  <h4 id = "show_convos" class="display_buttons">Show Messages</h4>
  <h4 id = "hide_convos" class="display_buttons">Hide Messages</h4>
  <div id ="conversation_box">     
      <!-- Continue Org Conversation -->
    <div class = "active_convos">  
      <h3>Active Conversations</h3>
      <% if @don.org_and_toy_connects.count != 0 %>
          <% @don.org_and_toy_connects.each do |t| %>
            <% if t.active == true %>
              <%= link_to t.donors_toy.toy.name, t, :class => "convo_link" %>
            <% end %>  
          <% end %>
        <% end %>
      <% if @don.don_and_seek_connects.count != 0 %>
        <% @don.don_and_seek_connects.each do |t| %>
          <% if t.active ==true %>
            <%= link_to t.seek.toy.name, t, :class => "convo_link" %>
          <% end %>  
        <% end %>
      <% end %>
    </div>
    <div class = "archived_convos">  
      <h3>Closed Conversations</h3>
      <% if @don.org_and_toy_connects.count != 0 %>
        <% @don.org_and_toy_connects.each do |t| %>
        <% if t.active == false %>
          <%= link_to t.donors_toy.toy.name, t, :class => "convo_link" %>
         <% end %> 
      <% end %>
    <% end %>
    <% if @don.don_and_seek_connects.count != 0 %>
      <% @don.don_and_seek_connects.each do |t| %>
        <% if t.active == false %>
          <%= link_to t.seek.toy.name, t, :class => "convo_link" %>
        <% end %>
      <% end %>
    <% end %>
  </div>
  </div>  
<% end %>
  

app/views/seeks/create.html.erb
<h1>Seeks#create</h1>
<p>Find me in app/views/seeks/create.html.erb</p>

app/views/seeks/destroy.html.erb
<h1>Seeks#destroy</h1>
<p>Find me in app/views/seeks/destroy.html.erb</p>

app/views/seeks/edit.html.erb
<h1>Seeks#edit</h1>
<p>Find me in app/views/seeks/edit.html.erb</p>

app/views/seeks/index.html.erb
<h1>Seeks#index</h1>
<% @seeks.each do |seek| %>
<%= link_to seek.toy.name, seek, :class => "link_to_buttons" %>
<%= link_to seek.organization.username, seek.organization, :class => "link_to_buttons" %>
<% end %>

app/views/seeks/new.html.erb
<% if logged_in_org? %>
<h1>Looking for a toy? Create A toy seek</h1>
<%= form_for @seek do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :comment %>
<%= f.text_area :comment %>
<%= f.hidden_field(:organization_id, :value => current_org.id)%>
<%= f.submit :create %>
<% end %>
<% else %>
<h1>Please Log in as an Organization to start seeking for a toy.</h1>
<% end %>

app/views/seeks/show.html.erb
<h1>Seek show Page</h1>
<%= @seek.toy.name %>
<%= image_tag @seek.toy.image.url(:thumb) %>
<%= link_to @seek.organization.username, @seek.organization, :class => "link_to_buttons" %>
<%= form_for(@donandseek) do |f| %>
  <% if logged_in_don? %>
  <div class="attending">
    <h3> Do you have this toy? Want to Donate?</h3>

    <div class="field">
       <%= f.hidden_field(:donator_id, :value => current_don.id) %>
    </div>
    <div>
      <%= f.hidden_field(:seek_id, :value => @seek.id)%>
    </div>
     <div>
      <%= f.submit "start a connection!", :class => "RSVP_button" %>
    </div>
  </div>
<% end %>
<% end %>

app/views/toys/edit.html.erb
<%= form_for @toy do |f| %>

<%= f.label :Organization_Donated_To %>
<% org_options = options_from_collection_for_select(@orgs, 'id', 'username') %>
<%= f.select :organization_id, org_options %>
<%= f.submit :Confirm %>
<% end %>

app/views/toys/index.html.erb
<h1 class= "headline">Toys Database</h1>
<h3> <%= link_to "Don't see the toy your looking for? Click here to create it!", new_toy_path, :class => "toy_link_buttons" %></h3>
<% @toys.each do |t| %>
	<div class = "toy_index_box">
		<%=link_to t.name, toy_path(t.id), method: :get, :class => "display_buttons" %>
		<%= link_to(image_tag(t.image.url(:thumb)), t, :class => "toy_link_to_img") %>
		<% if logged_in_don? %>
    		<%= form_for @donorstoy do |f| %>
      			<%= f.hidden_field(:donator_id, :value => current_don.id) %>
      			<%= f.hidden_field(:toy_id, :value => t.id)%>
      			<%= f.hidden_field(:active, :value => true) %>
      			<%= f.hidden_field(:sent, :value => false) %>
      			<%= f.submit "Donate!", :class => "RSVP_button" %>
    		<% end %>
  		<% end %>
  		<% if logged_in_org? %>
  			<%= form_for @seek do |f| %>
	      		<%= f.hidden_field(:organization_id, :value => current_org.id) %>
			     <%= f.hidden_field(:active, :value => true) %>
			     <%= f.hidden_field(:toy_id, :value => t.id)%>
			     <%= f.hidden_field(:sent, :value => false) %>
			     <%= f.submit "Request Toy!", :class => "request_button" %>
			<% end %>
		<% end %>
	</div>
<% end %>

app/views/toys/new.html.erb
<% if logged_in_don? || logged_in_org? %>
<%= form_for @toy do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :category %>
<%= f.select :category, ["Arts and Crafts", "Action Figures", "Board Games", "Dolls", "Educational Toys", "Electronics", "Puzzles", "Sports", "Other"] %>
<%= f.label :Age_range %>
<%= f.select :age_range, ["All Ages", "Baby: 0-12 Months", "Toddler: 1-3 Years", "Preschool 3-5 Years", "Adolescent 5-9 Years", "Preteen 9-12 Years", "Teen 12-15 Years"] %>
<%= f.label :image %>
<%= f.file_field :image %>
<%= f.label :description %>
<%= f.text_area :description %>
<%= f.submit :create %>
<% end %>
<% else %>
<h1>Please Log in to create a toy.</h1>
<% end %>

app/views/toys/show.html.erb
<h1 class="headline"><%= @toy.name %></h1>
<%= image_tag @toy.image.url(:medium), :class => "toy_img"%>
<div class = "toy_info">
  <h4>Category: <%= @toy.category %></h4>
  <h4>Age Range: <%= @toy.age_range %></h4>
  <h4>Description: <%= @toy.description %></h4>
</div>
<div class= "toy_donate_area">
  <% if logged_in_don? %>
    <h3> Do you have this toy? Want to Donate?</h3>
    <%= form_for @donorstoy do |f| %>
      <%= f.hidden_field(:donator_id, :value => current_don.id) %>
      <%= f.hidden_field(:toy_id, :value => @toy.id)%>
      <%= f.hidden_field(:active, :value => true) %>
      <%= f.hidden_field(:sent, :value => false) %>
      <%= f.submit "Donate!", :class => "RSVP_button" %>
    <% end %>
  <% end %>
</div>
<% if logged_in_org? %>
  <%= form_for @seek do |f| %>
    <h3> Do you want this toy?</h3>
      <%= f.hidden_field(:organization_id, :value => current_org.id) %>
      <%= f.hidden_field(:active, :value => true) %>
      <%= f.hidden_field(:toy_id, :value => @toy.id)%>
      <%= f.hidden_field(:sent, :value => false) %>
      <%= f.submit "Request Toy!", :class => "request_button" %>
  <% end %>
<% end %>