config/routes.rb
Rails.application.routes.draw do


 
  resources :organizations
  resources :seeks

  resources :donators
  resources :toys
  resources :donors_toys
  resources :don_and_seek_connects
  resources :org_and_toy_connects
  resources :comments_org_donor_toys
  resources :comments_don_and_seeks
  resources :received_toys
  resources :orgprofiles
  # You can have the root of your site routed with "root"
  root 'toys#index'
  get 'login' => 'sessions#new', as: :login
  post 'login_don' => 'sessions#create_don_session'
  post 'login_org' => 'sessions#create_org_session'
  patch 'update_toy' => 'toys#update', as: :update_toy
  delete 'logout' => 'sessions#destroy', as: :logout
  # get 'seeks' => 'seeks#index', as: :seeks_path 

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/don_and_seek_connect.rb
class DonAndSeekConnect < ActiveRecord::Base
	belongs_to :donator
	belongs_to :seek
	belongs_to :organization
	has_many :comments_don_and_seek
	has_many :received_toys
end

app/models/donator.rb
class Donator < ActiveRecord::Base
	has_secure_password

	# Paperclip below
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

	has_many :donors_toys
	has_many :toys, through: :donors_toys
	has_many :don_and_seek_connects
	has_many :seeks, through: :don_and_seeks_connects
	has_many :comments_org_donor_toys
	has_many :org_and_toy_connects
	has_many :comments_don_and_seeks
	has_many :received_toys

end

app/models/donors_toy.rb
class DonorsToy < ActiveRecord::Base
	
	belongs_to :donator
	belongs_to :toy
	has_many :organizations, through: :org_and_toy_connects
	has_many :org_and_toy_connects, dependent: :destroy
	has_many :received_toys

	# scope :multiple_donated_toys -> { |x,y| DonorsToy.where}
end

app/models/org_and_toy_connect.rb
class OrgAndToyConnect < ActiveRecord::Base
	belongs_to :organization
	belongs_to :donator
	belongs_to :donors_toy
	has_many :comments_org_donor_toys
	has_many :received_toys

end

app/models/org_profile.rb
class OrgProfile < ActiveRecord::Base
	belongs_to :organization
end

app/models/organization.rb
class Organization < ActiveRecord::Base
	has_secure_password

	# Paperclip below
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
	
	# Geocode Below
	geocoded_by :address
	after_validation :geocode

	# relationships
	has_many :seeks
	has_many :toys, through: :seeks
	has_many :org_and_toy_connects
	has_many :donors_toys, through: :org_and_toy_connects
	has_many :comments_org_donor_toys
	has_many :don_and_seek_connects
	has_many :comments_don_and_seeks
	has_many :received_toys
	has_one :org_profile
end

app/models/received_toy.rb
class ReceivedToy < ActiveRecord::Base
	belongs_to :organization
	belongs_to :donator
	belongs_to :donors_toy
	belongs_to :seek
	belongs_to :org_and_toy_connect
	belongs_to :don_and_seek_connect
end

app/models/seek.rb
class Seek < ActiveRecord::Base
	belongs_to :organization
	belongs_to :toy
	has_many :don_and_seek_connects, dependent: :destroy
	has_many :donators, through: :don_and_seek_connects
	has_many :received_toys
	
end

app/models/toy.rb
class Toy < ActiveRecord::Base
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  has_many :donors_toys
  has_many :donators, through: :donors_toys
  has_many :seeks
  has_many :organizations, through: :seeks

  # belongs_to :organization
end

app/controllers/seeks_controller.rb
class SeeksController < ApplicationController
  def index
    @seeks = Seek.all
  end

  def new
    @seek = Seek.new
  end

  def create
    @seek = Seek.new(seek_params)
    @seek.organization_id = current_org.id 
    @seek.toy_id = params[:seek][:toy_id]
    if @seek.save
      flash[:notice] = "Your seek was created."
      redirect_to @current_org
    else
      flash[:notice] = "There was a problem creating your seek."
      redirect_to :back
    end
  end

  def show
    @seek = Seek.find(params[:id])
    @donandseek = DonAndSeekConnect.new
  end

  def update
    @seek = Seek.find(params[:id])
    if @seek.update(seek_params)
      flash[:notice] = "Your toy has been marked as sent."
      redirect_to :back
    else
      flash[:notice] = "something went wrong. please try again."
      redirect_to :back
    end
  end

  def destroy
    @seek = Seek.find(params[:id])
    @seek.destroy
    flash[:notice] = "Your seek has been destroyed."
    redirect_to :back
  end

  private

  def seek_params
    params.require(:seek).permit( :organization_id, :toy_id, :comment, :active, :sent)
  end

end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
	def index
		@toys = Toy.all
		@donorstoy = DonorsToy.new
		@seek = Seek.new
	end

	def new
		@toy = Toy.new
	end

	def edit
		@toy = Toy.find(params[:id])
		@orgs = Organization.all
	end

	def update
		@toy = Toy.find(params[:id])
		@orgs = Organization.all
		if @toy.update_attributes(toy_params)
			flash[:notice] = "Your Donation has been saved!"
			redirect_to @toy
		else
			flash[:notice] = "something went wrong"
			redirect_to :back
		end
	end

	def create
		@toy = Toy.new(toy_params)
		if @toy.save
			flash[:notice] = "Your Toy Was Created"
			redirect_to @toy
		else
			flash[:notice] = "there was a problem creating your toy."
			redirect_to :back
		end
	end

	def show
		@toy = Toy.find(params[:id])
		@donorstoy = DonorsToy.new
		@seek = Seek.new
	end

	def destroy
		@toy = Toy.find(params[:id])
		@toy.destroy
		flash[:notice] = "Your toy has been deleted."
		redirect_to root_path
	end

	private
	def toy_params
  		params.require(:toy).permit(:name, :image, :donator_id, :donated?, :organization_id, :description, :category, :age_range)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donators_helper.rb
module DonatorsHelper
end

app/helpers/donors_toys_helper.rb
module DonorsToysHelper
end

app/helpers/org_profiles_helper.rb
module OrgProfilesHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/received_toys_helper.rb
module ReceivedToysHelper
end

app/helpers/seeks_helper.rb
module SeeksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToysApp</title>
  <link href='https://fonts.googleapis.com/css?family=Gloria+Hallelujah' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
    <nav>
      <ul>
        <li><%= link_to "Toys", toys_path, method: :get %></li>
        <li><%= link_to "Donors", donators_path, method: :get %></li>
        <li><%= link_to "Organizations", organizations_path, method: :get %></li>
        <% if logged_in_don? %>
        <li><%= link_to "My Profile", donator_path(current_don.id), method: :get %></li>
        <% end %>
        <% if logged_in_org? %>
        <li><%= link_to "My Profile", organization_path(current_org.id), method: :get %></li>
        <% end %>
      </ul>
    </nav>
    <div class = "welcome">
      <% if logged_in_don? %>
        <h4>Welcome, <%=current_don.username %></h4>
        <%= link_to("Sign Out", '/logout', method: :delete, class: "logout") %>
      <% elsif logged_in_org? %>
        <h4>Welcome, <%=current_org.username %></h4>
        <%= link_to("Sign Out", '/logout', method: :delete, class: "logout") %>
      <% else %>
        <%= link_to("Sign In", '/login', method: :get, class: "login")%>
        <%= link_to("Sign Up", new_donator_path, method: :get, class: "login")%>
      <% end -%>
    </div>
    <div id="container">
  	
    <% if flash[:notice] %>
    		<div><%= flash[:notice] %></div>
  	<% end %>
  	<% if flash[:alert] %>
    		<div><%= flash[:alert] %></div>
  	<% end %>

<%= yield %>
  </div>

</body>
</html>

app/views/user_notifier/send_comment_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Hi there <%= @user.username %>!</h1>
    <h3>You have received a new message regarding a toy you were discussing.</h3>
    <p><%= @comment.body %></p>
    <% if @comment.donator_id != nil %>
    	<p>from: <%= @comment.donator.username %> </p>
    <% else %>
    	<p>from: <%= @comment.organization.username%> </p>
    <% end %>		
  </body>
</html>